const APPROVE = 'APPROVE' as const;
const GET_TOKEN_BALANCE = 'GET_TOKEN_BALANCE' as const;
const GET_NATIVE_BALANCE = 'GET_NATIVE_BALANCE' as const;
const GET_RANK_ID = 'GET_RANK_ID' as const;
const UPDATE_USER_DATA = 'UPDATE_USER_DATA' as const;

export default {
  APPROVE,
  GET_TOKEN_BALANCE,
  GET_NATIVE_BALANCE,
  GET_RANK_ID,
  UPDATE_USER_DATA,
};
