const APPROVE = 'APPROVE' as const;
const GET_TOKEN_BALANCE = 'GET_TOKEN_BALANCE' as const;
const GET_NATIVE_BALANCE = 'GET_NATIVE_BALANCE' as const;

export default {
  APPROVE,
  GET_TOKEN_BALANCE,
  GET_NATIVE_BALANCE,
};
