const GET_IDO_LIST = 'GET_IDO_LIST' as const;
const GET_IDO_BY_ID = 'GET_IDO_BY_ID' as const;
const REGISTRATION_TO_IDO = 'REGISTRATION_TO_IDO' as const;
const GET_USER_ALLOCATION = 'GET_USER_ALLOCATION' as const;
const INVEST = 'INVEST' as const;
const GET_INVESTMENTS_INFO = 'GET_INVESTMENTS_INFO' as const;

export default {
  GET_IDO_LIST,
  GET_IDO_BY_ID,
  REGISTRATION_TO_IDO,
  GET_USER_ALLOCATION,
  INVEST,
  GET_INVESTMENTS_INFO,
};
