const GET_IDO_LIST = 'GET_IDO_LIST' as const;
const GET_IDO_BY_ID = 'GET_IDO_BY_ID' as const;
const REGISTRATION_TO_IDO = 'REGISTRATION_TO_IDO' as const;
const GET_USER_ALLOCATION = 'GET_USER_ALLOCATION' as const;
const INVEST = 'INVEST' as const;
const CLAIM = 'CLAIM' as const;
const REFUND = 'REFUND' as const;
const ADD_LIQUIDITY = 'ADD_LIQUIDITY' as const;
const GET_INVESTMENTS_INFO = 'GET_INVESTMENTS_INFO' as const;
const GET_TOTAL_BOUGHT = 'GET_TOTAL_BOUGHT' as const;

export default {
  GET_IDO_LIST,
  GET_IDO_BY_ID,
  REGISTRATION_TO_IDO,
  GET_USER_ALLOCATION,
  INVEST,
  CLAIM,
  REFUND,
  ADD_LIQUIDITY,
  GET_INVESTMENTS_INFO,
  GET_TOTAL_BOUGHT,
};
