const DEPOSIT = 'DEPOSIT' as const;
const CLAIM = 'CLAIM' as const;
const GET_USER_LOCKED_AMOUNT = 'GET_USER_LOCKED_AMOUNT' as const;
const GET_USER_UNLOCKED_AMOUNT = 'GET_USER_UNLOCKED_AMOUNT' as const;

export default {
  DEPOSIT,
  CLAIM,
  GET_USER_LOCKED_AMOUNT,
  GET_USER_UNLOCKED_AMOUNT,
};
