import { noop } from 'lodash';
import { Color } from 'types/api/enums';

import { LauncherCardProps } from './LauncherCard';

export const launcherCardPropsMocked: LauncherCardProps = {
  isRegistration: false,
  isGettingInvestmentsInfo: false,
  isCanAddLiquidity: false,
  isAddingLiquidity: false,
  isClaiming: false,
  onAddLiauidity: () => noop,
  projectData: {
    id: 1,
    timer: '1657700814',
    videoUrl: '',
    logoUrl: 'https://devcronos.rocknblock.io/media/logos/linkedin.png',
    projectName: 'KHB7sPwf',
    tokenName: 'IiQ8zh1eZX',
    tokenSymbol: 'IiQ',
    totalSupply: '9934514',
    tokenAddress: '0x43bA502a34D66BAd37122E84da4697B900Ef55d2',
    isPublic: false,
    vesting: false,
    startUnlockPercent: 0,
    unlockPercent: 0,
    unlockStepTime: 0,
    start: '1657700814',
    end: '1658305614',
    price: '53',
    status: 'PENDING',
    softCap: '77544',
    hardCap: '9934514',
    totalBought: '0',
    owner: 2,
    ownerAddress: '0x491539D6d1c59D1502c5a16dc6DF8D140a9dD177',
    discord: '',
    medium: '',
    telegram: '',
    twitter: '',
    tokenomics: [
      {
        title: '123',
        percent: 123,
        color: Color['#0A3B87'],
        id: 1,
      },
    ],
    partners: [],
    team: [],
    projectSummary: '',
    roadmap: '',
    tokenLogoUrl: '',
    investor: '',
    decimals: 18,
    investors: '',
    targetedRaise: '',
    withWeights: true,
    idoIncrement: 1,
  },
  userAllocation: '',
};
